### ISSUE TITLE
G and T missing from SVG folders ?

### ISSUE THREAD

**Issue by arnoo** [georgd/EB-Garamond-Initials#5]
Hello !

I have noticed that there are no files for G and T in the SVG folders. Am I missing something and is this normal, or is it a bug or error somewhere ?

**Comment by georgd** [comment]
Hi! The SVG folders are intermediate folders for contributions in SVG format. The actual font sources are in the SFD folders.

EDIT: Stopped telling the story in the middle, sorry. Uppercase G and T weren’t changed by @timgrei who (re-)did all the other glyphs, so they’re missing from the SVG folders.

**Comment by arnoo** [comment]
Sorry, I noticed I forgot to reply. Thanks a lot for explaining and for your work on this project !
