### ISSUE TITLE
Parentheses & Brackets Should Go Outside the Margin

### ISSUE THREAD

**Issue by amarz45** [georgd/EB-Garamond-Initials#6]
Followup to #1. When typesetting drop caps, the initial letter should be flush left and opening quotation marks, guillemets, parentheses, and brackets should be outside the body text into the left margin. For this font, this is already the case for quotation marks and guillements, but not for the parentheses, brackets, and top half brackets.

![import-2023-04-13_23:24:58](https://user-images.githubusercontent.com/92645199/231934135-f2ece966-6859-4135-8c84-a35fe30a331b.png)

**Comment by georgd** [comment]
That’s somewhat expected as I haven’t finished the implementation yet. I’m changing the logic for the positioning for a more sustainable solution.
